// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RareAPI_BE;

#nullable disable

namespace RareAPI_BE.Migrations
{
    [DbContext(typeof(RareAPI_BEDbContext))]
    partial class RareAPI_BEDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RareAPI_BE.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Great insights, Jon!",
                            PostId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Loved the music recommendations!",
                            PostId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Can't wait to visit Europe!",
                            PostId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Content = "This makes me so hungry!",
                            PostId = 4,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("RareAPI_BE.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Tech trends are rapidly shaping the future, with advancements in artificial intelligence (AI), blockchain, and quantum computing leading the way. AI continues to transform industries through automation, machine learning, and natural language processing, improving everything from customer service to medical diagnostics. Blockchain is disrupting finance and cybersecurity with decentralized systems that offer transparency and security, while quantum computing promises to revolutionize problem-solving in fields like cryptography and material science. The rise of 5G is also enabling faster, more connected networks, powering innovations like the Internet of Things (IoT) and smart cities. Additionally, advancements in virtual and augmented reality (VR/AR) are redefining how we experience entertainment, work, and education, creating immersive digital environments that are more integrated into daily life. These trends collectively push the boundaries of what's possible, signaling a tech-driven future with limitless potential.",
                            ImageUrl = "https://thehill.com/wp-content/uploads/sites/2/2018/05/robot_051018gn.jpg?w=960&h=540&crop=1",
                            Title = "Tech Trends 2024",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "The Northern Pines’ latest indie release, Wanderlust Echoes, is a refreshing blend of ethereal melodies and introspective lyrics that feels like wandering into a dream. With fragile yet resilient vocals from lead singer Jess Meyers, the album’s emotional rawness draws you in from the first track, \"Clouded Horizons.\" Songs like \"Midnight Runaway\" and \"Saltwater Skies\" showcase the band’s layered instrumentation and intricate attention to detail, weaving themes of self-discovery and escapism into each note. The standout track, \"Fading Trails,\" offers an addictive bassline and atmospheric synths, while \"Silver Shoreline\" provides a quieter, acoustic-driven moment of reflection. Though Wanderlust Echoes doesn’t stray far from the band’s earlier work, it feels like a natural progression, offering a beautifully human experience perfect for introspective moments or long drives. This is indie music at its finest.",
                            ImageUrl = "https://qph.cf2.quoracdn.net/main-qimg-7363ad9a5fb42cc0d1b1b35dd92135ac",
                            Title = "Best Indie Albums",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Exploring Europe is a journey through diverse cultures, rich history, and breathtaking landscapes that can feel like stepping into a living museum. From the bustling streets of Paris to the quiet canals of Venice, every city tells its own story through its architecture, cuisine, and local traditions. Whether you're hiking the Swiss Alps, relaxing on the beaches of Greece, or wandering through medieval castles in Germany, Europe offers something for every type of traveler. The continent’s seamless transportation system makes it easy to hop between countries, allowing you to experience the vibrant nightlife in Barcelona one day and the historical charm of Prague the next. Each destination offers its own unique flavor, yet there's a shared sense of history and connection that ties it all together, making Europe a dream destination for anyone with a thirst for adventure and discovery.",
                            ImageUrl = "https://i.cbc.ca/1.6729582.1674911696!/cumulusImage/httpImage/image.jpg_gen/derivatives/16x9_780/kitchener-homeless-encampment-victoria-and-weber-streets.jpg",
                            Title = "Exploring Europe",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Content = "Gourmet Delights is an innovative culinary creation that takes indulgence to a whole new level with its unique blend of exotic ingredients and unexpected flavors. Each dish in the Gourmet Delights line is meticulously crafted by expert chefs, combining rare spices from remote corners of the globe with organic, locally-sourced produce. The result is a menu that tantalizes the taste buds with surprising combinations like truffle-infused dragon fruit, caramelized cactus blossoms, and saffron-dusted seaweed crisps. Perfect for food enthusiasts seeking a luxurious dining experience, Gourmet Delights promises a flavor journey that pushes the boundaries of traditional cuisine, offering a mix of savory, sweet, and umami that’s truly unforgettable.",
                            ImageUrl = "https://gaianism.org/wp-content/uploads/2022/02/soylent-green-new-packaging1.png",
                            Title = "Gourmet Delights",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("RareAPI_BE.Models.PostTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PostId = 1,
                            TagId = 1
                        },
                        new
                        {
                            Id = 5,
                            PostId = 1,
                            TagId = 3
                        },
                        new
                        {
                            Id = 2,
                            PostId = 2,
                            TagId = 2
                        },
                        new
                        {
                            Id = 6,
                            PostId = 2,
                            TagId = 6
                        },
                        new
                        {
                            Id = 3,
                            PostId = 3,
                            TagId = 4
                        },
                        new
                        {
                            Id = 4,
                            PostId = 4,
                            TagId = 5
                        });
                });

            modelBuilder.Entity("RareAPI_BE.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lifestyle"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Health"
                        });
                });

            modelBuilder.Entity("RareAPI_BE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "The Pilsbury doughboy ain't got shit on me",
                            Email = "DoughMon@gmail.com",
                            ImageUrl = "https://images.playground.com/7344181b53c14f018042ea2a7ec1cc3e.jpeg",
                            Uid = "",
                            UserName = "JonDough"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "If bitches get stitches, what do good boys get?",
                            Email = "Mrthincrisp@gmail.com",
                            ImageUrl = "",
                            Uid = "xkZcuwDM5hXjHreMiKgs9AHVlcX2",
                            UserName = "Mrthincrisp"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Music is my life",
                            Email = "ross.morgan933@gmail.com",
                            ImageUrl = "",
                            Uid = "foSJhCcjadNP0TsmghEFzOt2GgX2",
                            UserName = "RossMorgan"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Traveler, blogger, coffee lover",
                            Email = "aspurlock@coding.com",
                            ImageUrl = "",
                            Uid = "Firebase_Key",
                            UserName = "AndrewSpurlock"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Tech geek with a passion for AI",
                            Email = "ChrisTechy@gmail.com",
                            ImageUrl = "https://www.southernliving.com/thmb/cxeGxYshY26hzmi5TToGS3oTraQ=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Lowes-Exterior-2000-9577c2caf665407083589a6cb2747301.jpg",
                            Uid = "",
                            UserName = "ChrisLowe"
                        });
                });

            modelBuilder.Entity("RareAPI_BE.Models.Comment", b =>
                {
                    b.HasOne("RareAPI_BE.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RareAPI_BE.Models.User", "User")
                        .WithMany("Comment")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RareAPI_BE.Models.Post", b =>
                {
                    b.HasOne("RareAPI_BE.Models.User", "User")
                        .WithMany("Post")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RareAPI_BE.Models.PostTag", b =>
                {
                    b.HasOne("RareAPI_BE.Models.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RareAPI_BE.Models.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("RareAPI_BE.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("RareAPI_BE.Models.Tag", b =>
                {
                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("RareAPI_BE.Models.User", b =>
                {
                    b.Navigation("Comment");

                    b.Navigation("Post");
                });
#pragma warning restore 612, 618
        }
    }
}
